# Generated by Django 5.2.8 on 2025-12-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
