# Generated by Django 5.2.8 on 2025-12-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_link_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
