# Generated by Django 5.2.8 on 2026-01-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
