# Generated by Django 6.0.1 on 2026-01-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_file_file_url_alter_file_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='video', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_urls', to='items.link')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
