# Generated by Django 6.0.1 on 2026-01-12 18:04

from django.db import migrations

def migrate_link_media_to_new_model(apps, schema_editor):
    Link = apps.get_model('items', 'Link')
    MediaURL = apps.get_model('items', 'MediaURL')

    # Iterate through all Link objects
    for link in Link.objects.filter(media_url__isnull=False):
        # Create a new MediaURL object for the existing media_url
        MediaURL.objects.create(
            link=link,
            url=link.media_url,
            media_type="video", # All existing media was a video
            order=0
        )

def reverse_migrate_link_media_to_new_model(apps, schema_editor):
    # This is a bit tricky, as you could have multiple new media URLs.
    # We will just move the first one back for the sake of a reversible migration.
    Link = apps.get_model('items', 'Link')

    # Iterate through all Link objects
    for link in Link.objects.all():
        first_media = link.media_urls.order_by('order').first()
        if first_media:
            link.media_url = first_media.url
            link.save(update_fields=['media_url'])

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_mediaurl'),
    ]

    operations = [
        migrations.RunPython(
            migrate_link_media_to_new_model, 
            reverse_migrate_link_media_to_new_model
        ),
    ]
