# Generated by Django 6.0.1 on 2026-01-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20260112_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaurl',
            name='hd_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaurl',
            name='sd_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
