# Generated by Django 6.0.1 on 2026-01-13 13:00

from django.db import migrations

def backfill_media_urls(apps, schema_editor):
    MediaURL = apps.get_model('items', 'MediaURL') # Ensure app name is correct
    for media in MediaURL.objects.all():
        # If the new fields are empty, fill them with the existing 'url'
        if not media.hd_url:
            media.hd_url = media.url
        if not media.sd_url:
            media.sd_url = media.url
        media.save()

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_mediaurl_hd_url_mediaurl_sd_url'),
    ]

    operations = [
        migrations.RunPython(backfill_media_urls),
    ]
